// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addCategoryUnit = `-- name: AddCategoryUnit :exec
INSERT INTO category_units (category_id, unit_id)
VALUES ($1, $2)
ON CONFLICT (category_id, unit_id) DO NOTHING
`

type AddCategoryUnitParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	UnitID     uuid.UUID `json:"unit_id"`
}

func (q *Queries) AddCategoryUnit(ctx context.Context, arg AddCategoryUnitParams) error {
	_, err := q.db.Exec(ctx, addCategoryUnit, arg.CategoryID, arg.UnitID)
	return err
}

const addCategoryVariant = `-- name: AddCategoryVariant :exec
INSERT INTO category_variants (category_id, variant_id)
VALUES ($1, $2)
ON CONFLICT (category_id, variant_id) DO NOTHING
`

type AddCategoryVariantParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	VariantID  uuid.UUID `json:"variant_id"`
}

func (q *Queries) AddCategoryVariant(ctx context.Context, arg AddCategoryVariantParams) error {
	_, err := q.db.Exec(ctx, addCategoryVariant, arg.CategoryID, arg.VariantID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (tenant_id, name, description, pricing_mode, markup_value)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, description, pricing_mode, markup_value, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	TenantID    uuid.UUID      `json:"tenant_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	PricingMode pgtype.Text    `json:"pricing_mode"`
	MarkupValue pgtype.Numeric `json:"markup_value"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.PricingMode,
		arg.MarkupValue,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.PricingMode,
		&i.MarkupValue,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateCategory = `-- name: DeactivateCategory :exec
UPDATE categories
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateCategory, id)
	return err
}

const deleteCategoryUnits = `-- name: DeleteCategoryUnits :exec
DELETE FROM category_units
WHERE category_id = $1
`

func (q *Queries) DeleteCategoryUnits(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoryUnits, categoryID)
	return err
}

const deleteCategoryVariants = `-- name: DeleteCategoryVariants :exec
DELETE FROM category_variants
WHERE category_id = $1
`

func (q *Queries) DeleteCategoryVariants(ctx context.Context, categoryID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategoryVariants, categoryID)
	return err
}

const getActiveCategoriesByTenant = `-- name: GetActiveCategoriesByTenant :many
SELECT id, tenant_id, name, description, pricing_mode, markup_value, is_active, created_at, updated_at FROM categories
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) GetActiveCategoriesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getActiveCategoriesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.PricingMode,
			&i.MarkupValue,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoriesByTenant = `-- name: GetCategoriesByTenant :many
SELECT id, tenant_id, name, description, pricing_mode, markup_value, is_active, created_at, updated_at FROM categories
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCategoriesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategoriesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.PricingMode,
			&i.MarkupValue,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, tenant_id, name, description, pricing_mode, markup_value, is_active, created_at, updated_at FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.PricingMode,
		&i.MarkupValue,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryUnits = `-- name: GetCategoryUnits :many
SELECT u.id, u.tenant_id, u.name, u.description, u.is_active, u.created_at, u.updated_at FROM units u
INNER JOIN category_units cu ON cu.unit_id = u.id
WHERE cu.category_id = $1
ORDER BY u.name ASC
`

func (q *Queries) GetCategoryUnits(ctx context.Context, categoryID uuid.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, getCategoryUnits, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryVariants = `-- name: GetCategoryVariants :many
SELECT v.id, v.tenant_id, v.name, v.description, v.is_active, v.created_at, v.updated_at FROM variants v
INNER JOIN category_variants cv ON cv.variant_id = v.id
WHERE cv.category_id = $1
ORDER BY v.name ASC
`

func (q *Queries) GetCategoryVariants(ctx context.Context, categoryID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, getCategoryVariants, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCategoryUnit = `-- name: RemoveCategoryUnit :exec
DELETE FROM category_units
WHERE category_id = $1 AND unit_id = $2
`

type RemoveCategoryUnitParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	UnitID     uuid.UUID `json:"unit_id"`
}

func (q *Queries) RemoveCategoryUnit(ctx context.Context, arg RemoveCategoryUnitParams) error {
	_, err := q.db.Exec(ctx, removeCategoryUnit, arg.CategoryID, arg.UnitID)
	return err
}

const removeCategoryVariant = `-- name: RemoveCategoryVariant :exec
DELETE FROM category_variants
WHERE category_id = $1 AND variant_id = $2
`

type RemoveCategoryVariantParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	VariantID  uuid.UUID `json:"variant_id"`
}

func (q *Queries) RemoveCategoryVariant(ctx context.Context, arg RemoveCategoryVariantParams) error {
	_, err := q.db.Exec(ctx, removeCategoryVariant, arg.CategoryID, arg.VariantID)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $1,
    description = $2,
    pricing_mode = $3,
    markup_value = $4,
    is_active = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING id, tenant_id, name, description, pricing_mode, markup_value, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	PricingMode pgtype.Text    `json:"pricing_mode"`
	MarkupValue pgtype.Numeric `json:"markup_value"`
	IsActive    bool           `json:"is_active"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Name,
		arg.Description,
		arg.PricingMode,
		arg.MarkupValue,
		arg.IsActive,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.PricingMode,
		&i.MarkupValue,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
