// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: features.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFeatureByID = `-- name: GetFeatureByID :one
SELECT id, parent_id, name, slug, module, actions, sort_order, created_at, updated_at FROM features
WHERE id = $1
`

func (q *Queries) GetFeatureByID(ctx context.Context, id uuid.UUID) (Feature, error) {
	row := q.db.QueryRow(ctx, getFeatureByID, id)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Module,
		&i.Actions,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureBySlug = `-- name: GetFeatureBySlug :one
SELECT id, parent_id, name, slug, module, actions, sort_order, created_at, updated_at FROM features
WHERE slug = $1
`

func (q *Queries) GetFeatureBySlug(ctx context.Context, slug string) (Feature, error) {
	row := q.db.QueryRow(ctx, getFeatureBySlug, slug)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Module,
		&i.Actions,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChildFeatures = `-- name: ListChildFeatures :many
SELECT id, parent_id, name, slug, module, actions, sort_order, created_at, updated_at FROM features
WHERE parent_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListChildFeatures(ctx context.Context, parentID pgtype.UUID) ([]Feature, error) {
	rows, err := q.db.Query(ctx, listChildFeatures, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Module,
			&i.Actions,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeatures = `-- name: ListFeatures :many
SELECT id, parent_id, name, slug, module, actions, sort_order, created_at, updated_at FROM features
ORDER BY sort_order ASC
`

func (q *Queries) ListFeatures(ctx context.Context) ([]Feature, error) {
	rows, err := q.db.Query(ctx, listFeatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feature{}
	for rows.Next() {
		var i Feature
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Module,
			&i.Actions,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeature = `-- name: UpsertFeature :one
INSERT INTO features (id, parent_id, name, slug, module, actions, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (slug)
DO UPDATE SET
    parent_id = EXCLUDED.parent_id,
    name = EXCLUDED.name,
    module = EXCLUDED.module,
    actions = EXCLUDED.actions,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW()
RETURNING id, parent_id, name, slug, module, actions, sort_order, created_at, updated_at
`

type UpsertFeatureParams struct {
	ID        uuid.UUID   `json:"id"`
	ParentID  pgtype.UUID `json:"parent_id"`
	Name      string      `json:"name"`
	Slug      string      `json:"slug"`
	Module    string      `json:"module"`
	Actions   []string    `json:"actions"`
	SortOrder int32       `json:"sort_order"`
}

func (q *Queries) UpsertFeature(ctx context.Context, arg UpsertFeatureParams) (Feature, error) {
	row := q.db.QueryRow(ctx, upsertFeature,
		arg.ID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Module,
		arg.Actions,
		arg.SortOrder,
	)
	var i Feature
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Module,
		&i.Actions,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
