// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (tenant_id, invited_by, email, role_id, store_ids, token_hash, status, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, 'pending', $7)
RETURNING id, tenant_id, invited_by, email, role_id, store_ids, token_hash, status, expires_at, created_at, updated_at
`

type CreateInvitationParams struct {
	TenantID  uuid.UUID          `json:"tenant_id"`
	InvitedBy uuid.UUID          `json:"invited_by"`
	Email     string             `json:"email"`
	RoleID    uuid.UUID          `json:"role_id"`
	StoreIds  []uuid.UUID        `json:"store_ids"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.TenantID,
		arg.InvitedBy,
		arg.Email,
		arg.RoleID,
		arg.StoreIds,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.RoleID,
		&i.StoreIds,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :exec
DELETE FROM invitations
WHERE id = $1
`

func (q *Queries) DeleteInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvitation, id)
	return err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, tenant_id, invited_by, email, role_id, store_ids, token_hash, status, expires_at, created_at, updated_at FROM invitations
WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id uuid.UUID) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.RoleID,
		&i.StoreIds,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, tenant_id, invited_by, email, role_id, store_ids, token_hash, status, expires_at, created_at, updated_at FROM invitations
WHERE token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.InvitedBy,
		&i.Email,
		&i.RoleID,
		&i.StoreIds,
		&i.TokenHash,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvitationsByEmail = `-- name: GetInvitationsByEmail :many
SELECT id, tenant_id, invited_by, email, role_id, store_ids, token_hash, status, expires_at, created_at, updated_at FROM invitations
WHERE email = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInvitationsByEmail(ctx context.Context, email string) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, getInvitationsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvitedBy,
			&i.Email,
			&i.RoleID,
			&i.StoreIds,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvitationsByTenant = `-- name: GetInvitationsByTenant :many
SELECT id, tenant_id, invited_by, email, role_id, store_ids, token_hash, status, expires_at, created_at, updated_at FROM invitations
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetInvitationsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, getInvitationsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invitation{}
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.InvitedBy,
			&i.Email,
			&i.RoleID,
			&i.StoreIds,
			&i.TokenHash,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvitationStatus = `-- name: UpdateInvitationStatus :exec
UPDATE invitations
SET status = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateInvitationStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) error {
	_, err := q.db.Exec(ctx, updateInvitationStatus, arg.Status, arg.ID)
	return err
}
