// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT rp.id, rp.role_id, rp.feature_id, rp.actions, rp.created_at, rp.updated_at, f.slug AS feature_slug, f.name AS feature_name, f.module AS feature_module
FROM role_permissions rp
INNER JOIN features f ON f.id = rp.feature_id
WHERE rp.role_id = $1
ORDER BY f.sort_order ASC
`

type GetRolePermissionsRow struct {
	ID            uuid.UUID          `json:"id"`
	RoleID        uuid.UUID          `json:"role_id"`
	FeatureID     uuid.UUID          `json:"feature_id"`
	Actions       []string           `json:"actions"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	FeatureSlug   string             `json:"feature_slug"`
	FeatureName   string             `json:"feature_name"`
	FeatureModule string             `json:"feature_module"`
}

func (q *Queries) GetRolePermissions(ctx context.Context, roleID uuid.UUID) ([]GetRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolePermissionsRow{}
	for rows.Next() {
		var i GetRolePermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleID,
			&i.FeatureID,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FeatureSlug,
			&i.FeatureName,
			&i.FeatureModule,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadUserPermissions = `-- name: LoadUserPermissions :many
SELECT f.slug AS feature_slug, rp.actions
FROM role_permissions rp
INNER JOIN user_roles ur ON ur.role_id = rp.role_id
INNER JOIN features f ON f.id = rp.feature_id
WHERE ur.user_id = $1
`

type LoadUserPermissionsRow struct {
	FeatureSlug string   `json:"feature_slug"`
	Actions     []string `json:"actions"`
}

func (q *Queries) LoadUserPermissions(ctx context.Context, userID uuid.UUID) ([]LoadUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, loadUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadUserPermissionsRow{}
	for rows.Next() {
		var i LoadUserPermissionsRow
		if err := rows.Scan(&i.FeatureSlug, &i.Actions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRolePermission = `-- name: SetRolePermission :one
INSERT INTO role_permissions (role_id, feature_id, actions)
VALUES ($1, $2, $3)
ON CONFLICT (role_id, feature_id)
DO UPDATE SET actions = EXCLUDED.actions, updated_at = NOW()
RETURNING id, role_id, feature_id, actions, created_at, updated_at
`

type SetRolePermissionParams struct {
	RoleID    uuid.UUID `json:"role_id"`
	FeatureID uuid.UUID `json:"feature_id"`
	Actions   []string  `json:"actions"`
}

func (q *Queries) SetRolePermission(ctx context.Context, arg SetRolePermissionParams) (RolePermission, error) {
	row := q.db.QueryRow(ctx, setRolePermission, arg.RoleID, arg.FeatureID, arg.Actions)
	var i RolePermission
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.FeatureID,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
