// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :one
INSERT INTO user_roles (user_id, role_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_id) DO NOTHING
RETURNING id, user_id, role_id, assigned_by, created_at, updated_at
`

type AssignUserRoleParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	RoleID     uuid.UUID   `json:"role_id"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, assignUserRole, arg.UserID, arg.RoleID, arg.AssignedBy)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (tenant_id, name, description, is_system_default)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, description, is_system_default, created_at, updated_at
`

type CreateRoleParams struct {
	TenantID        uuid.UUID   `json:"tenant_id"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	IsSystemDefault bool        `json:"is_system_default"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.IsSystemDefault,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystemDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, description, is_system_default, created_at, updated_at FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystemDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolesByTenant = `-- name: GetRolesByTenant :many
SELECT id, tenant_id, name, description, is_system_default, created_at, updated_at FROM roles
WHERE tenant_id = $1
ORDER BY is_system_default DESC, name ASC
`

func (q *Queries) GetRolesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsSystemDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSystemDefaultRole = `-- name: GetSystemDefaultRole :one
SELECT id, tenant_id, name, description, is_system_default, created_at, updated_at FROM roles
WHERE tenant_id = $1 AND is_system_default = TRUE
LIMIT 1
`

func (q *Queries) GetSystemDefaultRole(ctx context.Context, tenantID uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getSystemDefaultRole, tenantID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystemDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.tenant_id, r.name, r.description, r.is_system_default, r.created_at, r.updated_at FROM roles r
INNER JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetUserRoles(ctx context.Context, userID uuid.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsSystemDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasSystemDefaultRole = `-- name: HasSystemDefaultRole :one
SELECT EXISTS (
    SELECT 1 FROM user_roles ur
    INNER JOIN roles r ON r.id = ur.role_id
    WHERE ur.user_id = $1 AND r.is_system_default = TRUE
) AS has_default_role
`

func (q *Queries) HasSystemDefaultRole(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasSystemDefaultRole, userID)
	var has_default_role bool
	err := row.Scan(&has_default_role)
	return has_default_role, err
}

const unassignUserRole = `-- name: UnassignUserRole :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type UnassignUserRoleParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) UnassignUserRole(ctx context.Context, arg UnassignUserRoleParams) error {
	_, err := q.db.Exec(ctx, unassignUserRole, arg.UserID, arg.RoleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $1,
    description = $2,
    updated_at = NOW()
WHERE id = $3
RETURNING id, tenant_id, name, description, is_system_default, created_at, updated_at
`

type UpdateRoleParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystemDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
