// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stores.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserStore = `-- name: AssignUserStore :one
INSERT INTO user_stores (user_id, store_id, assigned_by)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, store_id) DO NOTHING
RETURNING id, user_id, store_id, assigned_by, created_at, updated_at
`

type AssignUserStoreParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	StoreID    uuid.UUID   `json:"store_id"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) AssignUserStore(ctx context.Context, arg AssignUserStoreParams) (UserStore, error) {
	row := q.db.QueryRow(ctx, assignUserStore, arg.UserID, arg.StoreID, arg.AssignedBy)
	var i UserStore
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreID,
		&i.AssignedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createStore = `-- name: CreateStore :one
INSERT INTO stores (tenant_id, name, address, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, address, phone, is_active, created_at, updated_at
`

type CreateStoreParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateStore = `-- name: DeactivateStore :exec
UPDATE stores
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateStore(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateStore, id)
	return err
}

const deleteUserStoresByUser = `-- name: DeleteUserStoresByUser :exec
DELETE FROM user_stores
WHERE user_id = $1
`

func (q *Queries) DeleteUserStoresByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserStoresByUser, userID)
	return err
}

const getStoreByID = `-- name: GetStoreByID :one
SELECT id, tenant_id, name, address, phone, is_active, created_at, updated_at FROM stores
WHERE id = $1
`

func (q *Queries) GetStoreByID(ctx context.Context, id uuid.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByID, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoresByTenant = `-- name: GetStoresByTenant :many
SELECT id, tenant_id, name, address, phone, is_active, created_at, updated_at FROM stores
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetStoresByTenant(ctx context.Context, tenantID uuid.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, getStoresByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStoreIDs = `-- name: GetUserStoreIDs :many
SELECT store_id FROM user_stores
WHERE user_id = $1
`

func (q *Queries) GetUserStoreIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getUserStoreIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var store_id uuid.UUID
		if err := rows.Scan(&store_id); err != nil {
			return nil, err
		}
		items = append(items, store_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStores = `-- name: GetUserStores :many
SELECT s.id, s.tenant_id, s.name, s.address, s.phone, s.is_active, s.created_at, s.updated_at FROM stores s
INNER JOIN user_stores us ON us.store_id = s.id
WHERE us.user_id = $1
ORDER BY s.created_at ASC
`

func (q *Queries) GetUserStores(ctx context.Context, userID uuid.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, getUserStores, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Store{}
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignUserStore = `-- name: UnassignUserStore :exec
DELETE FROM user_stores
WHERE user_id = $1 AND store_id = $2
`

type UnassignUserStoreParams struct {
	UserID  uuid.UUID `json:"user_id"`
	StoreID uuid.UUID `json:"store_id"`
}

func (q *Queries) UnassignUserStore(ctx context.Context, arg UnassignUserStoreParams) error {
	_, err := q.db.Exec(ctx, unassignUserStore, arg.UserID, arg.StoreID)
	return err
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores
SET name = $1,
    address = $2,
    phone = $3,
    is_active = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, tenant_id, name, address, phone, is_active, created_at, updated_at
`

type UpdateStoreParams struct {
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	IsActive bool        `json:"is_active"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.IsActive,
		arg.ID,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
