// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (tenant_id, name, contact_name, email, phone, address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, contact_name, email, phone, address, is_active, created_at, updated_at
`

type CreateSupplierParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	Name        string      `json:"name"`
	ContactName pgtype.Text `json:"contact_name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	Address     pgtype.Text `json:"address"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.TenantID,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateSupplier = `-- name: DeactivateSupplier :exec
UPDATE suppliers
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateSupplier(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateSupplier, id)
	return err
}

const getActiveSuppliersByTenant = `-- name: GetActiveSuppliersByTenant :many
SELECT id, tenant_id, name, contact_name, email, phone, address, is_active, created_at, updated_at FROM suppliers
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) GetActiveSuppliersByTenant(ctx context.Context, tenantID uuid.UUID) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, getActiveSuppliersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierByID = `-- name: GetSupplierByID :one
SELECT id, tenant_id, name, contact_name, email, phone, address, is_active, created_at, updated_at FROM suppliers
WHERE id = $1
`

func (q *Queries) GetSupplierByID(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByID, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSuppliersByTenant = `-- name: GetSuppliersByTenant :many
SELECT id, tenant_id, name, contact_name, email, phone, address, is_active, created_at, updated_at FROM suppliers
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetSuppliersByTenant(ctx context.Context, tenantID uuid.UUID) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, getSuppliersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.ContactName,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = $1,
    contact_name = $2,
    email = $3,
    phone = $4,
    address = $5,
    is_active = $6,
    updated_at = NOW()
WHERE id = $7
RETURNING id, tenant_id, name, contact_name, email, phone, address, is_active, created_at, updated_at
`

type UpdateSupplierParams struct {
	Name        string      `json:"name"`
	ContactName pgtype.Text `json:"contact_name"`
	Email       pgtype.Text `json:"email"`
	Phone       pgtype.Text `json:"phone"`
	Address     pgtype.Text `json:"address"`
	IsActive    bool        `json:"is_active"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Name,
		arg.ContactName,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.IsActive,
		arg.ID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.ContactName,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
