// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, is_active, created_at, updated_at
`

type CreateUnitParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit, arg.TenantID, arg.Name, arg.Description)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUnit = `-- name: DeactivateUnit :exec
UPDATE units
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUnit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUnit, id)
	return err
}

const getActiveUnitsByTenant = `-- name: GetActiveUnitsByTenant :many
SELECT id, tenant_id, name, description, is_active, created_at, updated_at FROM units
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) GetActiveUnitsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, getActiveUnitsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT id, tenant_id, name, description, is_active, created_at, updated_at FROM units
WHERE id = $1
`

func (q *Queries) GetUnitByID(ctx context.Context, id uuid.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnitByID, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnitsByTenant = `-- name: GetUnitsByTenant :many
SELECT id, tenant_id, name, description, is_active, created_at, updated_at FROM units
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetUnitsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, getUnitsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units
SET name = $1,
    description = $2,
    is_active = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, tenant_id, name, description, is_active, created_at, updated_at
`

type UpdateUnitParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
