// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: variants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVariant = `-- name: CreateVariant :one
INSERT INTO variants (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, is_active, created_at, updated_at
`

type CreateVariantParams struct {
	TenantID    uuid.UUID   `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, createVariant, arg.TenantID, arg.Name, arg.Description)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVariantValue = `-- name: CreateVariantValue :one
INSERT INTO variant_values (variant_id, value, sort_order)
VALUES ($1, $2, $3)
RETURNING id, variant_id, value, sort_order, is_active, created_at, updated_at
`

type CreateVariantValueParams struct {
	VariantID uuid.UUID `json:"variant_id"`
	Value     string    `json:"value"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateVariantValue(ctx context.Context, arg CreateVariantValueParams) (VariantValue, error) {
	row := q.db.QueryRow(ctx, createVariantValue, arg.VariantID, arg.Value, arg.SortOrder)
	var i VariantValue
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Value,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVariant = `-- name: DeactivateVariant :exec
UPDATE variants
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateVariant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateVariant, id)
	return err
}

const deleteVariantValue = `-- name: DeleteVariantValue :exec
DELETE FROM variant_values
WHERE id = $1
`

func (q *Queries) DeleteVariantValue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantValue, id)
	return err
}

const deleteVariantValuesByVariant = `-- name: DeleteVariantValuesByVariant :exec
DELETE FROM variant_values
WHERE variant_id = $1
`

func (q *Queries) DeleteVariantValuesByVariant(ctx context.Context, variantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantValuesByVariant, variantID)
	return err
}

const getActiveVariantsByTenant = `-- name: GetActiveVariantsByTenant :many
SELECT id, tenant_id, name, description, is_active, created_at, updated_at FROM variants
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) GetActiveVariantsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, getActiveVariantsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, tenant_id, name, description, is_active, created_at, updated_at FROM variants
WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, id)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantValues = `-- name: GetVariantValues :many
SELECT id, variant_id, value, sort_order, is_active, created_at, updated_at FROM variant_values
WHERE variant_id = $1
ORDER BY sort_order ASC, value ASC
`

func (q *Queries) GetVariantValues(ctx context.Context, variantID uuid.UUID) ([]VariantValue, error) {
	rows, err := q.db.Query(ctx, getVariantValues, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantValue{}
	for rows.Next() {
		var i VariantValue
		if err := rows.Scan(
			&i.ID,
			&i.VariantID,
			&i.Value,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantsByTenant = `-- name: GetVariantsByTenant :many
SELECT id, tenant_id, name, description, is_active, created_at, updated_at FROM variants
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetVariantsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Variant, error) {
	rows, err := q.db.Query(ctx, getVariantsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariant = `-- name: UpdateVariant :one
UPDATE variants
SET name = $1,
    description = $2,
    is_active = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, tenant_id, name, description, is_active, created_at, updated_at
`

type UpdateVariantParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, updateVariant,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.ID,
	)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariantValue = `-- name: UpdateVariantValue :one
UPDATE variant_values
SET value = $1,
    sort_order = $2,
    is_active = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, variant_id, value, sort_order, is_active, created_at, updated_at
`

type UpdateVariantValueParams struct {
	Value     string    `json:"value"`
	SortOrder int32     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateVariantValue(ctx context.Context, arg UpdateVariantValueParams) (VariantValue, error) {
	row := q.db.QueryRow(ctx, updateVariantValue,
		arg.Value,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	var i VariantValue
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Value,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
