// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: warehouses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWarehouse = `-- name: CreateWarehouse :one
INSERT INTO warehouses (tenant_id, name, address, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, name, address, phone, is_active, created_at, updated_at
`

type CreateWarehouseParams struct {
	TenantID uuid.UUID   `json:"tenant_id"`
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
}

func (q *Queries) CreateWarehouse(ctx context.Context, arg CreateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, createWarehouse,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWarehouse = `-- name: DeactivateWarehouse :exec
UPDATE warehouses
SET is_active = FALSE,
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateWarehouse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateWarehouse, id)
	return err
}

const getActiveWarehousesByTenant = `-- name: GetActiveWarehousesByTenant :many
SELECT id, tenant_id, name, address, phone, is_active, created_at, updated_at FROM warehouses
WHERE tenant_id = $1 AND is_active = TRUE
ORDER BY name ASC
`

func (q *Queries) GetActiveWarehousesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Warehouse, error) {
	rows, err := q.db.Query(ctx, getActiveWarehousesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warehouse{}
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWarehouseByID = `-- name: GetWarehouseByID :one
SELECT id, tenant_id, name, address, phone, is_active, created_at, updated_at FROM warehouses
WHERE id = $1
`

func (q *Queries) GetWarehouseByID(ctx context.Context, id uuid.UUID) (Warehouse, error) {
	row := q.db.QueryRow(ctx, getWarehouseByID, id)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWarehousesByTenant = `-- name: GetWarehousesByTenant :many
SELECT id, tenant_id, name, address, phone, is_active, created_at, updated_at FROM warehouses
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetWarehousesByTenant(ctx context.Context, tenantID uuid.UUID) ([]Warehouse, error) {
	rows, err := q.db.Query(ctx, getWarehousesByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Warehouse{}
	for rows.Next() {
		var i Warehouse
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWarehouse = `-- name: UpdateWarehouse :one
UPDATE warehouses
SET name = $1,
    address = $2,
    phone = $3,
    is_active = $4,
    updated_at = NOW()
WHERE id = $5
RETURNING id, tenant_id, name, address, phone, is_active, created_at, updated_at
`

type UpdateWarehouseParams struct {
	Name     string      `json:"name"`
	Address  pgtype.Text `json:"address"`
	Phone    pgtype.Text `json:"phone"`
	IsActive bool        `json:"is_active"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateWarehouse(ctx context.Context, arg UpdateWarehouseParams) (Warehouse, error) {
	row := q.db.QueryRow(ctx, updateWarehouse,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.IsActive,
		arg.ID,
	)
	var i Warehouse
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
